# Graph Configuration

[graph]
# Define the relationships between different agent types
logical_to_technical = true
technical_to_kinematic = true
kinematic_to_dynamics = true

[visualization]
# Configuration for graph visualization
enable_real_time = true
update_frequency_ms = 100
max_history_points = 1000

[constraints]
# Global constraints for the system
max_agents_per_type = 100
simulation_time_step = 0.01  # seconds
