[package]
name = "path_planner"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rdkafka = { version = "0.29", features = ["tokio-runtime"] }
chrono = "0.4"
