[workspace]
members = [
    "crates/core",
    "crates/pathfinder",
    "crates/simulator",
    "crates/server",
    "crates/viewer-wasm",
    "crates/utilities",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
version = "0.1.0"
authors = ["Gryphon Project Contributors"]

[workspace.dependencies]
prost = "0.13"
prost-types = "0.13"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
axum = { version = "0.7", features = ["ws"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
futures = "0.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
rand = "0.8"
anyhow = "1"
tokio-tungstenite = "0.21"

[workspace.metadata.cargo-udeps.ignore]
# Add crates to ignore if unused detection is noisy