# resources/path_planning/manifest.toml

[[maps]]
name = "sample_map"
source = "geojson/sample_map.geojson"
graph = "graphs/sample_map.graph.bin"
version = "v1"
source_sha256 = "TODO"
created_at = "2025-08-18T00:00:00Z"
description = "Tiny example map used for tests and local development."
