name: Postgres Integration Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  pg-integration:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5433:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run Postgres integration tests
        env:
          PG_TEST_PORT: 5433
        run: |
          cargo test --features pg_integration -- tests::pg_integration_tests -- --nocapture
